services:
  uvicorn-service:
    build: .
    container_name: uvicorn_service
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./app:/app

  locust:
    image: locustio/locust
    container_name: locust_load_test
    ports:
      - "8089:8089"  
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    working_dir: /mnt/locust
    environment:
      - LOCUST_HOST=http://uvicorn_service:8000
    depends_on:
      - uvicorn-service